name: Pi Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: gforceinnovation/sf-ci:latest
      credentials:
        username: gforceinnovation
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: SF CLI version
        run: sf --version

      - name: SF CLI plugins
        run: sf plugins

      - name: System info
        run: |
          uname -a
          node --version
          java -version
          jq --version
